# filepath: ~/.dbt/profiles.yml
snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ZAZKHHD-BL75038
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE') }}"
      database: "{{ env_var('SF_DATABASE') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      schema: "{{ env_var('SF_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: false
